
# Generated by CodiumAI
from mock import patch
from face_crop import print_folders


import unittest

class TestPrintFolders(unittest.TestCase):

    # Tests that the function prints a list of folders when given a non-empty list of folders
    def test_print_folders_with_non_empty_list(self):
        folders = ['folder1', 'folder2', 'folder3']
        with patch('builtins.print') as mock_print:
            print_folders(folders)
            mock_print.assert_called_once_with(f"This is the full list of folders to crop the images of: {folders}")

    # Tests that the function prints "No folders to print." when given an empty list
    def test_print_folders_with_empty_list(self):
        folders = []
        with patch('builtins.print') as mock_print:
            print_folders(folders)
            mock_print.assert_called_once_with("No folders to print.")

    # Tests that the function returns None when given None
    def test_print_folders_with_none(self):
        folders = None
        result = print_folders(folders)
        self.assertIsNone(result)

    # Tests that the function prints "No folders to print." when given an empty string
    def test_print_folders_with_empty_string(self):
        folders = ""
        with patch('builtins.print') as mock_print:
            print_folders(folders)
            mock_print.assert_called_once_with("No folders to print.")

    # Tests that the function prints "No folders to print." when given a non-list object
    def test_print_folders_with_non_list_object(self):
        folders = 123
        with patch('builtins.print') as mock_print:
            print_folders(folders)
            mock_print.assert_called_once_with("No folders to print.")

    # Tests that the function prints a list of folders with duplicates
    def test_print_folders_with_duplicates(self):
        folders = ['folder1', 'folder2', 'folder1']
        with patch('builtins.print') as mock_print:
            print_folders(folders)
            mock_print.assert_called_once_with(f"This is the full list of folders to crop the images of: {folders}")