
# Generated by CodiumAI
from face_crop import remove_folders


import unittest

class TestRemoveFolders(unittest.TestCase):

    # Tests that the function can successfully remove a folder that exists in the list
    def test_remove_existing_folder(self):
        folders = ['folder1', 'folder2', 'folder3']
        folder_name = 'folder2'
        expected_folders = ['folder1', 'folder3']

        remove_folders()
    
        self.assertEqual(folders, expected_folders)

    # Tests that the function can successfully remove multiple folders that exist in the list
    def test_remove_multiple_folders(self):
        folders = ['folder1', 'folder2', 'folder3', 'folder4']
        folder_name = 'folder'
        expected_folders = []

        remove_folders()
    
        self.assertEqual(folders, expected_folders)

    # Tests that the function can successfully remove a folder that has the same name as another folder in the list
    def test_remove_folder_same_name(self):
        folders = ['folder1', 'folder2', 'folder3', 'folder3']
        folder_name = 'folder3'
        expected_folders = ['folder1', 'folder2']

        remove_folders()
    
        self.assertEqual(folders, expected_folders)

    # Tests that the function can successfully remove a folder with different capitalization than the input
    def test_remove_folder_different_capitalization(self):
        folders = ['folder1', 'folder2', 'folder3']
        folder_name = 'Folder2'
        expected_folders = ['folder1', 'folder3']

        remove_folders()
    
        self.assertEqual(folders, expected_folders)

    # Tests that the function handles the case when no folders are present in the list
    def test_remove_no_folders(self):
        folders = []
        folder_name = 'folder'
        expected_folders = []

        remove_folders()
    
        self.assertEqual(folders, expected_folders)

    # Tests that the function can successfully remove all folders in the list
    def test_remove_all_folders(self):
        folders = ['folder1', 'folder2', 'folder3']
        folder_name = 'folder'
        expected_folders = []

        remove_folders()
    
        self.assertEqual(folders, expected_folders)