
# Generated by CodiumAI
from face_crop import list_folders


import unittest

class TestListFolders(unittest.TestCase):

    # Tests that the function retrieves all folders in a given directory
    def test_retrieve_all_folders_in_directory(self):
        folder_path = "path/to/directory"
        expected_folders = ["path/to/directory/folder1", "path/to/directory/folder2", "path/to/directory/folder3"]
    
        result = list_folders(folder_path)
    
        self.assertEqual(result, expected_folders)

    # Tests that the function retrieves all folders in a given directory without subdirectories
    def test_retrieve_folders_in_directory_without_subdirectories(self):
        folder_path = "path/to/directory"
        expected_folders = ["path/to/directory/folder1", "path/to/directory/folder2", "path/to/directory/folder3"]
    
        result = list_folders(folder_path, include_subdirectories=False)
    
        self.assertEqual(result, expected_folders)

    # Tests that the function retrieves folders in an empty directory
    def test_retrieve_folders_in_empty_directory(self):
        folder_path = "path/to/empty_directory"
        expected_folders = []
    
        result = list_folders(folder_path)
    
        self.assertEqual(result, expected_folders)

    # Tests that the function retrieves folders in a directory with only files
    def test_retrieve_folders_in_directory_with_only_files(self):
        folder_path = "path/to/directory_with_only_files"
        expected_folders = []
    
        result = list_folders(folder_path)
    
        self.assertEqual(result, expected_folders)

    # Tests that the function retrieves folders in a directory with only hidden files
    def test_retrieve_folders_in_directory_with_only_hidden_files(self):
        folder_path = "path/to/directory_with_only_hidden_files"
        expected_folders = []
    
        result = list_folders(folder_path)
    
        self.assertEqual(result, expected_folders)

    # Tests that the function retrieves folders in a directory with only hidden folders
    def test_retrieve_folders_in_directory_with_only_hidden_folders(self):
        folder_path = "path/to/directory_with_only_hidden_folders"
        expected_folders = []
    
        result = list_folders(folder_path)
    
        self.assertEqual(result, expected_folders)