
# Generated by CodiumAI
import io
import sys
from face_crop import search_folders
import builtins


import unittest

class TestSearchFolders(unittest.TestCase):

    # Tests that the function checks and prints the stored folder names correctly
    def test_check_stored_folder_names(self):
        # Arrange
        folders = ['folder1', 'folder2', 'folder3']
        expected_output = "Folders:\nfolder1\nfolder2\nfolder3\n"
        captured_output = io.StringIO()
        sys.stdout = captured_output

        # Act
        search_folders()

        # Assert
        self.assertEqual(captured_output.getvalue(), expected_output)

    # Tests that the function prompts the user to add a folder to the list correctly
    def test_change_folders_add_folder(self):
        # Arrange
        folders = []
        user_input = "y"
        expected_output = "Enter the path of the root directory you want to start from: "
        captured_output = io.StringIO()
        sys.stdout = captured_output
        builtins.input = lambda _: user_input

        # Act
        search_folders()

        # Assert
        self.assertEqual(captured_output.getvalue(), expected_output)

    # Tests that the function prompts the user to remove a folder from the list correctly
    def test_change_folders_remove_folder(self):
        # Arrange
        folders = ['folder1', 'folder2', 'folder3']
        user_input = "y"
        expected_output = "Please type in the name of the folder that you don't want on the list anymore: "
        captured_output = io.StringIO()
        sys.stdout = captured_output
        builtins.input = lambda _: user_input

        # Act
        search_folders()

        # Assert
        self.assertEqual(captured_output.getvalue(), expected_output)

    # Tests that the function prompts the user to remove all folders from the list correctly
    def test_change_folders_remove_all_folders(self):
        # Arrange
        folders = ['folder1', 'folder2', 'folder3']
        user_input = "2"
        expected_output = "Did you want to remove something from the list or the entire list? Please enter 1 to remove something or 2 to remove the entire list: "
        captured_output = io.StringIO()
        sys.stdout = captured_output
        builtins.input = lambda _: user_input

        # Act
        search_folders()

        # Assert
        self.assertEqual(captured_output.getvalue(), expected_output)

    # Tests that the function prompts the user to make no changes to the folder list correctly
    def test_change_folders_no_changes(self):
        # Arrange
        folders = []
        user_input = "n"
        expected_output = "Is there anything that you would like to change about this list? (y/n): "
        captured_output = io.StringIO()
        sys.stdout = captured_output
        builtins.input = lambda _: user_input

        # Act
        search_folders()

        # Assert
        self.assertEqual(captured_output.getvalue(), expected_output)

    # Tests that the function prompts the user to make multiple changes to the folder list correctly
    def test_change_folders_multiple_changes(self):
        # Arrange
        folders = ['folder1', 'folder2', 'folder3']
        user_input = "y"
        expected_output = "You would like to change the list! How did you want to change it? Please enter 1 to add, 2 to remove: "
        captured_output = io.StringIO()
        sys.stdout = captured_output
        builtins.input = lambda _: user_input

        # Act
        search_folders()

        # Assert
        self.assertEqual(captured_output.getvalue(), expected_output)